export const DISTRIBUTORS: string[] = [
  "Not distributed",
  "DistroKid",
  "TuneCore",
  "CD Baby",
  "Ditto Music",
  "RouteNote",
  "Amuse",
  "ONErpm",
  "Too Lost",
  "LANDR Distribution",
  "Soundrop",
  "UnitedMasters",
  "FreshTunes",
  "iMusician",
  "Horus Music",
  "Record Union",
  "Music Gateway",
  "Repost by SoundCloud",
  "Level Music",
  "Boost Collective",
  "Anti-Joy",
  "Feiyr",
  "MusicAlligator",
  "Symphonic Distribution",
  "Songtradr",
  "OffStep",
  "Gyrostream",
  "Catapult",
  "Zimbalam",
  "Spinnup",
  "EmuBands",
  "MondoTunes",
  "MusicDiffusion",
  "Indiefy",
  "Delivermytune",
  "DistroDirect",
  "NotaDist",
  "AWAL",
  "FUGA",
  "The Orchard",
  "Believe Distribution",
  "Virgin Music Group",
  "ADA (Alternative Distribution Alliance)",
  "INgrooves",
  "Stem",
  "Empire Distribution",
  "Identity Music",
  "Idol",
  "Absolute Label Services",
  "Redeye Worldwide",
  "Human Re Sources",
  "Paradise Worldwide",
  "Kontor New Media",
  "Zebralution",
  "Xelon Entertainment",
  "Cargo Records",
  "Republic of Music",
  "Orchard Enterprises",
  "Secretly Distribution",
  "PIAS Distribution",
  "Proper Music Distribution",
  "Kobalt AWAL",
  "Ditto Label Services",
  "SonoSuite",
  "Revelator",
  "Label Engine",
  "Consolidated Independent",
  "MusicHub",
  "Paradise PRO",
  "SourceAudio",
  "Base for Music",
  "Vydia",
  "Synchtank",
  "state51",
  "CI Media Cloud",
  "Reprtoir",
  "LabelGrid",
  "Vistex Rights Platform",
  "Session Studio Platform",
  "Curve Royalty Systems",
  "SR1",
  "Exactuals",
  "MusicMaster",
  "Universal Music Group Distribution",
  "Sony Music Distribution",
  "Warner Music Distribution",
  "Caroline International (Legacy)",
  "EMI Distribution (Legacy)",
  "Others",
];
