/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YoutubeContentIdRouteImport } from './routes/youtube-content-id'
import { Route as YoutubeCmsRouteImport } from './routes/youtube-cms'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapReleasesDotxmlRouteImport } from './routes/sitemap-releases[.]xml'
import { Route as SitemapProfilesDotxmlRouteImport } from './routes/sitemap-profiles[.]xml'
import { Route as SitemapMainDotxmlRouteImport } from './routes/sitemap-main[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PublishingRouteImport } from './routes/publishing'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as MusicPromotionRouteImport } from './routes/music-promotion'
import { Route as FreeMusicDistributionRouteImport } from './routes/free-music-distribution'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlankRouteImport } from './routes/blank'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiToolsRouteImport } from './routes/ai-tools'
import { Route as AdvancedInsightsRouteImport } from './routes/advanced-insights'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalRefundRouteImport } from './routes/legal/refund'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalPagesRouteImport } from './routes/legal/pages'
import { Route as LegalEditorialRouteImport } from './routes/legal/editorial'
import { Route as LegalDmcaRouteImport } from './routes/legal/dmca'
import { Route as LSlugRouteImport } from './routes/l.$slug'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiDspLookupRouteImport } from './routes/api/dsp-lookup'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRoyaltiesRouteImport } from './routes/_authenticated/royalties'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedReleasesRouteImport } from './routes/_authenticated/releases'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlatformSettingsRouteImport } from './routes/_authenticated/platform-settings'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as AuthenticatedArtistsRouteImport } from './routes/_authenticated/artists'
import { Route as AuthenticatedApprovalQueueRouteImport } from './routes/_authenticated/approval-queue'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAccountingRouteImport } from './routes/_authenticated/accounting'
import { Route as RoleTypeUsernameRouteImport } from './routes/$roleType.$username'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users.index'
import { Route as AuthenticatedReleasesIndexRouteImport } from './routes/_authenticated/releases.index'
import { Route as AuthenticatedUsersUsernameRouteImport } from './routes/_authenticated/users.$username'
import { Route as AuthenticatedToolsDspLookupRouteImport } from './routes/_authenticated/tools.dsp-lookup'
import { Route as AuthenticatedReleasesNewRouteImport } from './routes/_authenticated/releases.new'
import { Route as AuthenticatedReleasesIdRouteImport } from './routes/_authenticated/releases.$id'
import { Route as AuthenticatedAdminTicketsRouteImport } from './routes/_authenticated/admin.tickets'
import { Route as AuthenticatedAdminSeoRouteImport } from './routes/_authenticated/admin.seo'
import { Route as AuthenticatedAdminPagesRouteImport } from './routes/_authenticated/admin.pages'
import { Route as AuthenticatedAdminBroadcastRouteImport } from './routes/_authenticated/admin.broadcast'
import { Route as ApiPublicHooksSeoIndexQueueRouteImport } from './routes/api/public/hooks/seo-index-queue'
import { Route as ApiPublicDspWebhookPlatformRouteImport } from './routes/api/public/dsp-webhook/$platform'
import { Route as AuthenticatedAdminPagesIdRouteImport } from './routes/_authenticated/admin.pages.$id'

const YoutubeContentIdRoute = YoutubeContentIdRouteImport.update({
  id: '/youtube-content-id',
  path: '/youtube-content-id',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeCmsRoute = YoutubeCmsRouteImport.update({
  id: '/youtube-cms',
  path: '/youtube-cms',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapReleasesDotxmlRoute = SitemapReleasesDotxmlRouteImport.update({
  id: '/sitemap-releases.xml',
  path: '/sitemap-releases.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapProfilesDotxmlRoute = SitemapProfilesDotxmlRouteImport.update({
  id: '/sitemap-profiles.xml',
  path: '/sitemap-profiles.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapMainDotxmlRoute = SitemapMainDotxmlRouteImport.update({
  id: '/sitemap-main.xml',
  path: '/sitemap-main.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishingRoute = PublishingRouteImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicPromotionRoute = MusicPromotionRouteImport.update({
  id: '/music-promotion',
  path: '/music-promotion',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeMusicDistributionRoute = FreeMusicDistributionRouteImport.update({
  id: '/free-music-distribution',
  path: '/free-music-distribution',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlankRoute = BlankRouteImport.update({
  id: '/blank',
  path: '/blank',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiToolsRoute = AiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedInsightsRoute = AdvancedInsightsRouteImport.update({
  id: '/advanced-insights',
  path: '/advanced-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/legal/refund',
  path: '/legal/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPagesRoute = LegalPagesRouteImport.update({
  id: '/legal/pages',
  path: '/legal/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalEditorialRoute = LegalEditorialRouteImport.update({
  id: '/legal/editorial',
  path: '/legal/editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDmcaRoute = LegalDmcaRouteImport.update({
  id: '/legal/dmca',
  path: '/legal/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const LSlugRoute = LSlugRouteImport.update({
  id: '/l/$slug',
  path: '/l/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDspLookupRoute = ApiDspLookupRouteImport.update({
  id: '/api/dsp-lookup',
  path: '/api/dsp-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoyaltiesRoute = AuthenticatedRoyaltiesRouteImport.update({
  id: '/royalties',
  path: '/royalties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReleasesRoute = AuthenticatedReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformSettingsRoute =
  AuthenticatedPlatformSettingsRouteImport.update({
    id: '/platform-settings',
    path: '/platform-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArtistsRoute = AuthenticatedArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalQueueRoute =
  AuthenticatedApprovalQueueRouteImport.update({
    id: '/approval-queue',
    path: '/approval-queue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountingRoute = AuthenticatedAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const RoleTypeUsernameRoute = RoleTypeUsernameRouteImport.update({
  id: '/$roleType/$username',
  path: '/$roleType/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReleasesIndexRoute =
  AuthenticatedReleasesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReleasesRoute,
  } as any)
const AuthenticatedUsersUsernameRoute =
  AuthenticatedUsersUsernameRouteImport.update({
    id: '/users/$username',
    path: '/users/$username',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsDspLookupRoute =
  AuthenticatedToolsDspLookupRouteImport.update({
    id: '/dsp-lookup',
    path: '/dsp-lookup',
    getParentRoute: () => AuthenticatedToolsRoute,
  } as any)
const AuthenticatedReleasesNewRoute =
  AuthenticatedReleasesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedReleasesRoute,
  } as any)
const AuthenticatedReleasesIdRoute = AuthenticatedReleasesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedReleasesRoute,
} as any)
const AuthenticatedAdminTicketsRoute =
  AuthenticatedAdminTicketsRouteImport.update({
    id: '/admin/tickets',
    path: '/admin/tickets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSeoRoute = AuthenticatedAdminSeoRouteImport.update({
  id: '/admin/seo',
  path: '/admin/seo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPagesRoute = AuthenticatedAdminPagesRouteImport.update({
  id: '/admin/pages',
  path: '/admin/pages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminBroadcastRoute =
  AuthenticatedAdminBroadcastRouteImport.update({
    id: '/admin/broadcast',
    path: '/admin/broadcast',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksSeoIndexQueueRoute =
  ApiPublicHooksSeoIndexQueueRouteImport.update({
    id: '/api/public/hooks/seo-index-queue',
    path: '/api/public/hooks/seo-index-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDspWebhookPlatformRoute =
  ApiPublicDspWebhookPlatformRouteImport.update({
    id: '/api/public/dsp-webhook/$platform',
    path: '/api/public/dsp-webhook/$platform',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminPagesIdRoute =
  AuthenticatedAdminPagesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminPagesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advanced-insights': typeof AdvancedInsightsRoute
  '/ai-tools': typeof AiToolsRoute
  '/auth': typeof AuthRoute
  '/blank': typeof BlankRoute
  '/contact': typeof ContactRoute
  '/free-music-distribution': typeof FreeMusicDistributionRoute
  '/music-promotion': typeof MusicPromotionRoute
  '/pending': typeof PendingRoute
  '/publishing': typeof PublishingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-main.xml': typeof SitemapMainDotxmlRoute
  '/sitemap-profiles.xml': typeof SitemapProfilesDotxmlRoute
  '/sitemap-releases.xml': typeof SitemapReleasesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sync': typeof SyncRoute
  '/youtube-cms': typeof YoutubeCmsRoute
  '/youtube-content-id': typeof YoutubeContentIdRoute
  '/$roleType/$username': typeof RoleTypeUsernameRoute
  '/accounting': typeof AuthenticatedAccountingRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/approval-queue': typeof AuthenticatedApprovalQueueRoute
  '/artists': typeof AuthenticatedArtistsRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/platform-settings': typeof AuthenticatedPlatformSettingsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/releases': typeof AuthenticatedReleasesRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/royalties': typeof AuthenticatedRoyaltiesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tools': typeof AuthenticatedToolsRouteWithChildren
  '/api/dsp-lookup': typeof ApiDspLookupRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/l/$slug': typeof LSlugRoute
  '/legal/dmca': typeof LegalDmcaRoute
  '/legal/editorial': typeof LegalEditorialRoute
  '/legal/pages': typeof LegalPagesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/p/$slug': typeof PSlugRoute
  '/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRouteWithChildren
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/releases/$id': typeof AuthenticatedReleasesIdRoute
  '/releases/new': typeof AuthenticatedReleasesNewRoute
  '/tools/dsp-lookup': typeof AuthenticatedToolsDspLookupRoute
  '/users/$username': typeof AuthenticatedUsersUsernameRoute
  '/releases/': typeof AuthenticatedReleasesIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/admin/pages/$id': typeof AuthenticatedAdminPagesIdRoute
  '/api/public/dsp-webhook/$platform': typeof ApiPublicDspWebhookPlatformRoute
  '/api/public/hooks/seo-index-queue': typeof ApiPublicHooksSeoIndexQueueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advanced-insights': typeof AdvancedInsightsRoute
  '/ai-tools': typeof AiToolsRoute
  '/auth': typeof AuthRoute
  '/blank': typeof BlankRoute
  '/contact': typeof ContactRoute
  '/free-music-distribution': typeof FreeMusicDistributionRoute
  '/music-promotion': typeof MusicPromotionRoute
  '/pending': typeof PendingRoute
  '/publishing': typeof PublishingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-main.xml': typeof SitemapMainDotxmlRoute
  '/sitemap-profiles.xml': typeof SitemapProfilesDotxmlRoute
  '/sitemap-releases.xml': typeof SitemapReleasesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sync': typeof SyncRoute
  '/youtube-cms': typeof YoutubeCmsRoute
  '/youtube-content-id': typeof YoutubeContentIdRoute
  '/$roleType/$username': typeof RoleTypeUsernameRoute
  '/accounting': typeof AuthenticatedAccountingRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/approval-queue': typeof AuthenticatedApprovalQueueRoute
  '/artists': typeof AuthenticatedArtistsRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/platform-settings': typeof AuthenticatedPlatformSettingsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/royalties': typeof AuthenticatedRoyaltiesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tools': typeof AuthenticatedToolsRouteWithChildren
  '/api/dsp-lookup': typeof ApiDspLookupRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/l/$slug': typeof LSlugRoute
  '/legal/dmca': typeof LegalDmcaRoute
  '/legal/editorial': typeof LegalEditorialRoute
  '/legal/pages': typeof LegalPagesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/p/$slug': typeof PSlugRoute
  '/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRouteWithChildren
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/releases/$id': typeof AuthenticatedReleasesIdRoute
  '/releases/new': typeof AuthenticatedReleasesNewRoute
  '/tools/dsp-lookup': typeof AuthenticatedToolsDspLookupRoute
  '/users/$username': typeof AuthenticatedUsersUsernameRoute
  '/releases': typeof AuthenticatedReleasesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/admin/pages/$id': typeof AuthenticatedAdminPagesIdRoute
  '/api/public/dsp-webhook/$platform': typeof ApiPublicDspWebhookPlatformRoute
  '/api/public/hooks/seo-index-queue': typeof ApiPublicHooksSeoIndexQueueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/advanced-insights': typeof AdvancedInsightsRoute
  '/ai-tools': typeof AiToolsRoute
  '/auth': typeof AuthRoute
  '/blank': typeof BlankRoute
  '/contact': typeof ContactRoute
  '/free-music-distribution': typeof FreeMusicDistributionRoute
  '/music-promotion': typeof MusicPromotionRoute
  '/pending': typeof PendingRoute
  '/publishing': typeof PublishingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-main.xml': typeof SitemapMainDotxmlRoute
  '/sitemap-profiles.xml': typeof SitemapProfilesDotxmlRoute
  '/sitemap-releases.xml': typeof SitemapReleasesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sync': typeof SyncRoute
  '/youtube-cms': typeof YoutubeCmsRoute
  '/youtube-content-id': typeof YoutubeContentIdRoute
  '/$roleType/$username': typeof RoleTypeUsernameRoute
  '/_authenticated/accounting': typeof AuthenticatedAccountingRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/approval-queue': typeof AuthenticatedApprovalQueueRoute
  '/_authenticated/artists': typeof AuthenticatedArtistsRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/platform-settings': typeof AuthenticatedPlatformSettingsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/releases': typeof AuthenticatedReleasesRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/royalties': typeof AuthenticatedRoyaltiesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRouteWithChildren
  '/api/dsp-lookup': typeof ApiDspLookupRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/l/$slug': typeof LSlugRoute
  '/legal/dmca': typeof LegalDmcaRoute
  '/legal/editorial': typeof LegalEditorialRoute
  '/legal/pages': typeof LegalPagesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/p/$slug': typeof PSlugRoute
  '/_authenticated/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/_authenticated/admin/pages': typeof AuthenticatedAdminPagesRouteWithChildren
  '/_authenticated/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/_authenticated/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/_authenticated/releases/$id': typeof AuthenticatedReleasesIdRoute
  '/_authenticated/releases/new': typeof AuthenticatedReleasesNewRoute
  '/_authenticated/tools/dsp-lookup': typeof AuthenticatedToolsDspLookupRoute
  '/_authenticated/users/$username': typeof AuthenticatedUsersUsernameRoute
  '/_authenticated/releases/': typeof AuthenticatedReleasesIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/admin/pages/$id': typeof AuthenticatedAdminPagesIdRoute
  '/api/public/dsp-webhook/$platform': typeof ApiPublicDspWebhookPlatformRoute
  '/api/public/hooks/seo-index-queue': typeof ApiPublicHooksSeoIndexQueueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advanced-insights'
    | '/ai-tools'
    | '/auth'
    | '/blank'
    | '/contact'
    | '/free-music-distribution'
    | '/music-promotion'
    | '/pending'
    | '/publishing'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap-main.xml'
    | '/sitemap-profiles.xml'
    | '/sitemap-releases.xml'
    | '/sitemap.xml'
    | '/sync'
    | '/youtube-cms'
    | '/youtube-content-id'
    | '/$roleType/$username'
    | '/accounting'
    | '/analytics'
    | '/approval-queue'
    | '/artists'
    | '/catalog'
    | '/dashboard'
    | '/help'
    | '/platform-settings'
    | '/profile'
    | '/releases'
    | '/reports'
    | '/royalties'
    | '/settings'
    | '/support'
    | '/tools'
    | '/api/dsp-lookup'
    | '/api/generate-image'
    | '/l/$slug'
    | '/legal/dmca'
    | '/legal/editorial'
    | '/legal/pages'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/p/$slug'
    | '/admin/broadcast'
    | '/admin/pages'
    | '/admin/seo'
    | '/admin/tickets'
    | '/releases/$id'
    | '/releases/new'
    | '/tools/dsp-lookup'
    | '/users/$username'
    | '/releases/'
    | '/users/'
    | '/admin/pages/$id'
    | '/api/public/dsp-webhook/$platform'
    | '/api/public/hooks/seo-index-queue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advanced-insights'
    | '/ai-tools'
    | '/auth'
    | '/blank'
    | '/contact'
    | '/free-music-distribution'
    | '/music-promotion'
    | '/pending'
    | '/publishing'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap-main.xml'
    | '/sitemap-profiles.xml'
    | '/sitemap-releases.xml'
    | '/sitemap.xml'
    | '/sync'
    | '/youtube-cms'
    | '/youtube-content-id'
    | '/$roleType/$username'
    | '/accounting'
    | '/analytics'
    | '/approval-queue'
    | '/artists'
    | '/catalog'
    | '/dashboard'
    | '/help'
    | '/platform-settings'
    | '/profile'
    | '/reports'
    | '/royalties'
    | '/settings'
    | '/support'
    | '/tools'
    | '/api/dsp-lookup'
    | '/api/generate-image'
    | '/l/$slug'
    | '/legal/dmca'
    | '/legal/editorial'
    | '/legal/pages'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/p/$slug'
    | '/admin/broadcast'
    | '/admin/pages'
    | '/admin/seo'
    | '/admin/tickets'
    | '/releases/$id'
    | '/releases/new'
    | '/tools/dsp-lookup'
    | '/users/$username'
    | '/releases'
    | '/users'
    | '/admin/pages/$id'
    | '/api/public/dsp-webhook/$platform'
    | '/api/public/hooks/seo-index-queue'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/advanced-insights'
    | '/ai-tools'
    | '/auth'
    | '/blank'
    | '/contact'
    | '/free-music-distribution'
    | '/music-promotion'
    | '/pending'
    | '/publishing'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap-main.xml'
    | '/sitemap-profiles.xml'
    | '/sitemap-releases.xml'
    | '/sitemap.xml'
    | '/sync'
    | '/youtube-cms'
    | '/youtube-content-id'
    | '/$roleType/$username'
    | '/_authenticated/accounting'
    | '/_authenticated/analytics'
    | '/_authenticated/approval-queue'
    | '/_authenticated/artists'
    | '/_authenticated/catalog'
    | '/_authenticated/dashboard'
    | '/_authenticated/help'
    | '/_authenticated/platform-settings'
    | '/_authenticated/profile'
    | '/_authenticated/releases'
    | '/_authenticated/reports'
    | '/_authenticated/royalties'
    | '/_authenticated/settings'
    | '/_authenticated/support'
    | '/_authenticated/tools'
    | '/api/dsp-lookup'
    | '/api/generate-image'
    | '/l/$slug'
    | '/legal/dmca'
    | '/legal/editorial'
    | '/legal/pages'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/p/$slug'
    | '/_authenticated/admin/broadcast'
    | '/_authenticated/admin/pages'
    | '/_authenticated/admin/seo'
    | '/_authenticated/admin/tickets'
    | '/_authenticated/releases/$id'
    | '/_authenticated/releases/new'
    | '/_authenticated/tools/dsp-lookup'
    | '/_authenticated/users/$username'
    | '/_authenticated/releases/'
    | '/_authenticated/users/'
    | '/_authenticated/admin/pages/$id'
    | '/api/public/dsp-webhook/$platform'
    | '/api/public/hooks/seo-index-queue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdvancedInsightsRoute: typeof AdvancedInsightsRoute
  AiToolsRoute: typeof AiToolsRoute
  AuthRoute: typeof AuthRoute
  BlankRoute: typeof BlankRoute
  ContactRoute: typeof ContactRoute
  FreeMusicDistributionRoute: typeof FreeMusicDistributionRoute
  MusicPromotionRoute: typeof MusicPromotionRoute
  PendingRoute: typeof PendingRoute
  PublishingRoute: typeof PublishingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapMainDotxmlRoute: typeof SitemapMainDotxmlRoute
  SitemapProfilesDotxmlRoute: typeof SitemapProfilesDotxmlRoute
  SitemapReleasesDotxmlRoute: typeof SitemapReleasesDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SyncRoute: typeof SyncRoute
  YoutubeCmsRoute: typeof YoutubeCmsRoute
  YoutubeContentIdRoute: typeof YoutubeContentIdRoute
  RoleTypeUsernameRoute: typeof RoleTypeUsernameRoute
  ApiDspLookupRoute: typeof ApiDspLookupRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  LSlugRoute: typeof LSlugRoute
  LegalDmcaRoute: typeof LegalDmcaRoute
  LegalEditorialRoute: typeof LegalEditorialRoute
  LegalPagesRoute: typeof LegalPagesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalTermsRoute: typeof LegalTermsRoute
  PSlugRoute: typeof PSlugRoute
  ApiPublicDspWebhookPlatformRoute: typeof ApiPublicDspWebhookPlatformRoute
  ApiPublicHooksSeoIndexQueueRoute: typeof ApiPublicHooksSeoIndexQueueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youtube-content-id': {
      id: '/youtube-content-id'
      path: '/youtube-content-id'
      fullPath: '/youtube-content-id'
      preLoaderRoute: typeof YoutubeContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube-cms': {
      id: '/youtube-cms'
      path: '/youtube-cms'
      fullPath: '/youtube-cms'
      preLoaderRoute: typeof YoutubeCmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-releases.xml': {
      id: '/sitemap-releases.xml'
      path: '/sitemap-releases.xml'
      fullPath: '/sitemap-releases.xml'
      preLoaderRoute: typeof SitemapReleasesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-profiles.xml': {
      id: '/sitemap-profiles.xml'
      path: '/sitemap-profiles.xml'
      fullPath: '/sitemap-profiles.xml'
      preLoaderRoute: typeof SitemapProfilesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-main.xml': {
      id: '/sitemap-main.xml'
      path: '/sitemap-main.xml'
      fullPath: '/sitemap-main.xml'
      preLoaderRoute: typeof SitemapMainDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publishing': {
      id: '/publishing'
      path: '/publishing'
      fullPath: '/publishing'
      preLoaderRoute: typeof PublishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music-promotion': {
      id: '/music-promotion'
      path: '/music-promotion'
      fullPath: '/music-promotion'
      preLoaderRoute: typeof MusicPromotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-music-distribution': {
      id: '/free-music-distribution'
      path: '/free-music-distribution'
      fullPath: '/free-music-distribution'
      preLoaderRoute: typeof FreeMusicDistributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blank': {
      id: '/blank'
      path: '/blank'
      fullPath: '/blank'
      preLoaderRoute: typeof BlankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tools': {
      id: '/ai-tools'
      path: '/ai-tools'
      fullPath: '/ai-tools'
      preLoaderRoute: typeof AiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced-insights': {
      id: '/advanced-insights'
      path: '/advanced-insights'
      fullPath: '/advanced-insights'
      preLoaderRoute: typeof AdvancedInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refund': {
      id: '/legal/refund'
      path: '/legal/refund'
      fullPath: '/legal/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/pages': {
      id: '/legal/pages'
      path: '/legal/pages'
      fullPath: '/legal/pages'
      preLoaderRoute: typeof LegalPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/editorial': {
      id: '/legal/editorial'
      path: '/legal/editorial'
      fullPath: '/legal/editorial'
      preLoaderRoute: typeof LegalEditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/dmca': {
      id: '/legal/dmca'
      path: '/legal/dmca'
      fullPath: '/legal/dmca'
      preLoaderRoute: typeof LegalDmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l/$slug': {
      id: '/l/$slug'
      path: '/l/$slug'
      fullPath: '/l/$slug'
      preLoaderRoute: typeof LSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dsp-lookup': {
      id: '/api/dsp-lookup'
      path: '/api/dsp-lookup'
      fullPath: '/api/dsp-lookup'
      preLoaderRoute: typeof ApiDspLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/royalties': {
      id: '/_authenticated/royalties'
      path: '/royalties'
      fullPath: '/royalties'
      preLoaderRoute: typeof AuthenticatedRoyaltiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/releases': {
      id: '/_authenticated/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof AuthenticatedReleasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform-settings': {
      id: '/_authenticated/platform-settings'
      path: '/platform-settings'
      fullPath: '/platform-settings'
      preLoaderRoute: typeof AuthenticatedPlatformSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/artists': {
      id: '/_authenticated/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof AuthenticatedArtistsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approval-queue': {
      id: '/_authenticated/approval-queue'
      path: '/approval-queue'
      fullPath: '/approval-queue'
      preLoaderRoute: typeof AuthenticatedApprovalQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounting': {
      id: '/_authenticated/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AuthenticatedAccountingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/$roleType/$username': {
      id: '/$roleType/$username'
      path: '/$roleType/$username'
      fullPath: '/$roleType/$username'
      preLoaderRoute: typeof RoleTypeUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/releases/': {
      id: '/_authenticated/releases/'
      path: '/'
      fullPath: '/releases/'
      preLoaderRoute: typeof AuthenticatedReleasesIndexRouteImport
      parentRoute: typeof AuthenticatedReleasesRoute
    }
    '/_authenticated/users/$username': {
      id: '/_authenticated/users/$username'
      path: '/users/$username'
      fullPath: '/users/$username'
      preLoaderRoute: typeof AuthenticatedUsersUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/dsp-lookup': {
      id: '/_authenticated/tools/dsp-lookup'
      path: '/dsp-lookup'
      fullPath: '/tools/dsp-lookup'
      preLoaderRoute: typeof AuthenticatedToolsDspLookupRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
    '/_authenticated/releases/new': {
      id: '/_authenticated/releases/new'
      path: '/new'
      fullPath: '/releases/new'
      preLoaderRoute: typeof AuthenticatedReleasesNewRouteImport
      parentRoute: typeof AuthenticatedReleasesRoute
    }
    '/_authenticated/releases/$id': {
      id: '/_authenticated/releases/$id'
      path: '/$id'
      fullPath: '/releases/$id'
      preLoaderRoute: typeof AuthenticatedReleasesIdRouteImport
      parentRoute: typeof AuthenticatedReleasesRoute
    }
    '/_authenticated/admin/tickets': {
      id: '/_authenticated/admin/tickets'
      path: '/admin/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/seo': {
      id: '/_authenticated/admin/seo'
      path: '/admin/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AuthenticatedAdminSeoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pages': {
      id: '/_authenticated/admin/pages'
      path: '/admin/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthenticatedAdminPagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/broadcast': {
      id: '/_authenticated/admin/broadcast'
      path: '/admin/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AuthenticatedAdminBroadcastRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/seo-index-queue': {
      id: '/api/public/hooks/seo-index-queue'
      path: '/api/public/hooks/seo-index-queue'
      fullPath: '/api/public/hooks/seo-index-queue'
      preLoaderRoute: typeof ApiPublicHooksSeoIndexQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dsp-webhook/$platform': {
      id: '/api/public/dsp-webhook/$platform'
      path: '/api/public/dsp-webhook/$platform'
      fullPath: '/api/public/dsp-webhook/$platform'
      preLoaderRoute: typeof ApiPublicDspWebhookPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/pages/$id': {
      id: '/_authenticated/admin/pages/$id'
      path: '/$id'
      fullPath: '/admin/pages/$id'
      preLoaderRoute: typeof AuthenticatedAdminPagesIdRouteImport
      parentRoute: typeof AuthenticatedAdminPagesRoute
    }
  }
}

interface AuthenticatedReleasesRouteChildren {
  AuthenticatedReleasesIdRoute: typeof AuthenticatedReleasesIdRoute
  AuthenticatedReleasesNewRoute: typeof AuthenticatedReleasesNewRoute
  AuthenticatedReleasesIndexRoute: typeof AuthenticatedReleasesIndexRoute
}

const AuthenticatedReleasesRouteChildren: AuthenticatedReleasesRouteChildren = {
  AuthenticatedReleasesIdRoute: AuthenticatedReleasesIdRoute,
  AuthenticatedReleasesNewRoute: AuthenticatedReleasesNewRoute,
  AuthenticatedReleasesIndexRoute: AuthenticatedReleasesIndexRoute,
}

const AuthenticatedReleasesRouteWithChildren =
  AuthenticatedReleasesRoute._addFileChildren(
    AuthenticatedReleasesRouteChildren,
  )

interface AuthenticatedToolsRouteChildren {
  AuthenticatedToolsDspLookupRoute: typeof AuthenticatedToolsDspLookupRoute
}

const AuthenticatedToolsRouteChildren: AuthenticatedToolsRouteChildren = {
  AuthenticatedToolsDspLookupRoute: AuthenticatedToolsDspLookupRoute,
}

const AuthenticatedToolsRouteWithChildren =
  AuthenticatedToolsRoute._addFileChildren(AuthenticatedToolsRouteChildren)

interface AuthenticatedAdminPagesRouteChildren {
  AuthenticatedAdminPagesIdRoute: typeof AuthenticatedAdminPagesIdRoute
}

const AuthenticatedAdminPagesRouteChildren: AuthenticatedAdminPagesRouteChildren =
  {
    AuthenticatedAdminPagesIdRoute: AuthenticatedAdminPagesIdRoute,
  }

const AuthenticatedAdminPagesRouteWithChildren =
  AuthenticatedAdminPagesRoute._addFileChildren(
    AuthenticatedAdminPagesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountingRoute: typeof AuthenticatedAccountingRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedApprovalQueueRoute: typeof AuthenticatedApprovalQueueRoute
  AuthenticatedArtistsRoute: typeof AuthenticatedArtistsRoute
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedPlatformSettingsRoute: typeof AuthenticatedPlatformSettingsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReleasesRoute: typeof AuthenticatedReleasesRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRoyaltiesRoute: typeof AuthenticatedRoyaltiesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRouteWithChildren
  AuthenticatedAdminBroadcastRoute: typeof AuthenticatedAdminBroadcastRoute
  AuthenticatedAdminPagesRoute: typeof AuthenticatedAdminPagesRouteWithChildren
  AuthenticatedAdminSeoRoute: typeof AuthenticatedAdminSeoRoute
  AuthenticatedAdminTicketsRoute: typeof AuthenticatedAdminTicketsRoute
  AuthenticatedUsersUsernameRoute: typeof AuthenticatedUsersUsernameRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountingRoute: AuthenticatedAccountingRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedApprovalQueueRoute: AuthenticatedApprovalQueueRoute,
  AuthenticatedArtistsRoute: AuthenticatedArtistsRoute,
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedPlatformSettingsRoute: AuthenticatedPlatformSettingsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReleasesRoute: AuthenticatedReleasesRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRoyaltiesRoute: AuthenticatedRoyaltiesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRouteWithChildren,
  AuthenticatedAdminBroadcastRoute: AuthenticatedAdminBroadcastRoute,
  AuthenticatedAdminPagesRoute: AuthenticatedAdminPagesRouteWithChildren,
  AuthenticatedAdminSeoRoute: AuthenticatedAdminSeoRoute,
  AuthenticatedAdminTicketsRoute: AuthenticatedAdminTicketsRoute,
  AuthenticatedUsersUsernameRoute: AuthenticatedUsersUsernameRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdvancedInsightsRoute: AdvancedInsightsRoute,
  AiToolsRoute: AiToolsRoute,
  AuthRoute: AuthRoute,
  BlankRoute: BlankRoute,
  ContactRoute: ContactRoute,
  FreeMusicDistributionRoute: FreeMusicDistributionRoute,
  MusicPromotionRoute: MusicPromotionRoute,
  PendingRoute: PendingRoute,
  PublishingRoute: PublishingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapMainDotxmlRoute: SitemapMainDotxmlRoute,
  SitemapProfilesDotxmlRoute: SitemapProfilesDotxmlRoute,
  SitemapReleasesDotxmlRoute: SitemapReleasesDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SyncRoute: SyncRoute,
  YoutubeCmsRoute: YoutubeCmsRoute,
  YoutubeContentIdRoute: YoutubeContentIdRoute,
  RoleTypeUsernameRoute: RoleTypeUsernameRoute,
  ApiDspLookupRoute: ApiDspLookupRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  LSlugRoute: LSlugRoute,
  LegalDmcaRoute: LegalDmcaRoute,
  LegalEditorialRoute: LegalEditorialRoute,
  LegalPagesRoute: LegalPagesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalTermsRoute: LegalTermsRoute,
  PSlugRoute: PSlugRoute,
  ApiPublicDspWebhookPlatformRoute: ApiPublicDspWebhookPlatformRoute,
  ApiPublicHooksSeoIndexQueueRoute: ApiPublicHooksSeoIndexQueueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
