/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LSlugRouteImport } from './routes/l.$slug'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiDspLookupRouteImport } from './routes/api/dsp-lookup'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRoyaltiesRouteImport } from './routes/_authenticated/royalties'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedReleasesRouteImport } from './routes/_authenticated/releases'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlatformSettingsRouteImport } from './routes/_authenticated/platform-settings'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as AuthenticatedArtistsRouteImport } from './routes/_authenticated/artists'
import { Route as AuthenticatedApprovalQueueRouteImport } from './routes/_authenticated/approval-queue'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedToolsDspLookupRouteImport } from './routes/_authenticated/tools.dsp-lookup'
import { Route as AuthenticatedReleasesNewRouteImport } from './routes/_authenticated/releases.new'
import { Route as AuthenticatedReleasesIdRouteImport } from './routes/_authenticated/releases.$id'
import { Route as AuthenticatedAdminTicketsRouteImport } from './routes/_authenticated/admin.tickets'
import { Route as ApiPublicDspWebhookPlatformRouteImport } from './routes/api/public/dsp-webhook/$platform'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LSlugRoute = LSlugRouteImport.update({
  id: '/l/$slug',
  path: '/l/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDspLookupRoute = ApiDspLookupRouteImport.update({
  id: '/api/dsp-lookup',
  path: '/api/dsp-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoyaltiesRoute = AuthenticatedRoyaltiesRouteImport.update({
  id: '/royalties',
  path: '/royalties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReleasesRoute = AuthenticatedReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformSettingsRoute =
  AuthenticatedPlatformSettingsRouteImport.update({
    id: '/platform-settings',
    path: '/platform-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArtistsRoute = AuthenticatedArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalQueueRoute =
  AuthenticatedApprovalQueueRouteImport.update({
    id: '/approval-queue',
    path: '/approval-queue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolsDspLookupRoute =
  AuthenticatedToolsDspLookupRouteImport.update({
    id: '/dsp-lookup',
    path: '/dsp-lookup',
    getParentRoute: () => AuthenticatedToolsRoute,
  } as any)
const AuthenticatedReleasesNewRoute =
  AuthenticatedReleasesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedReleasesRoute,
  } as any)
const AuthenticatedReleasesIdRoute = AuthenticatedReleasesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedReleasesRoute,
} as any)
const AuthenticatedAdminTicketsRoute =
  AuthenticatedAdminTicketsRouteImport.update({
    id: '/admin/tickets',
    path: '/admin/tickets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicDspWebhookPlatformRoute =
  ApiPublicDspWebhookPlatformRouteImport.update({
    id: '/api/public/dsp-webhook/$platform',
    path: '/api/public/dsp-webhook/$platform',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/approval-queue': typeof AuthenticatedApprovalQueueRoute
  '/artists': typeof AuthenticatedArtistsRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/platform-settings': typeof AuthenticatedPlatformSettingsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/releases': typeof AuthenticatedReleasesRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/royalties': typeof AuthenticatedRoyaltiesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tools': typeof AuthenticatedToolsRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/api/dsp-lookup': typeof ApiDspLookupRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/l/$slug': typeof LSlugRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/releases/$id': typeof AuthenticatedReleasesIdRoute
  '/releases/new': typeof AuthenticatedReleasesNewRoute
  '/tools/dsp-lookup': typeof AuthenticatedToolsDspLookupRoute
  '/api/public/dsp-webhook/$platform': typeof ApiPublicDspWebhookPlatformRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/approval-queue': typeof AuthenticatedApprovalQueueRoute
  '/artists': typeof AuthenticatedArtistsRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/platform-settings': typeof AuthenticatedPlatformSettingsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/releases': typeof AuthenticatedReleasesRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/royalties': typeof AuthenticatedRoyaltiesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tools': typeof AuthenticatedToolsRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/api/dsp-lookup': typeof ApiDspLookupRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/l/$slug': typeof LSlugRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/releases/$id': typeof AuthenticatedReleasesIdRoute
  '/releases/new': typeof AuthenticatedReleasesNewRoute
  '/tools/dsp-lookup': typeof AuthenticatedToolsDspLookupRoute
  '/api/public/dsp-webhook/$platform': typeof ApiPublicDspWebhookPlatformRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/approval-queue': typeof AuthenticatedApprovalQueueRoute
  '/_authenticated/artists': typeof AuthenticatedArtistsRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/platform-settings': typeof AuthenticatedPlatformSettingsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/releases': typeof AuthenticatedReleasesRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/royalties': typeof AuthenticatedRoyaltiesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/api/dsp-lookup': typeof ApiDspLookupRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/l/$slug': typeof LSlugRoute
  '/_authenticated/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/_authenticated/releases/$id': typeof AuthenticatedReleasesIdRoute
  '/_authenticated/releases/new': typeof AuthenticatedReleasesNewRoute
  '/_authenticated/tools/dsp-lookup': typeof AuthenticatedToolsDspLookupRoute
  '/api/public/dsp-webhook/$platform': typeof ApiPublicDspWebhookPlatformRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pending'
    | '/reset-password'
    | '/analytics'
    | '/approval-queue'
    | '/artists'
    | '/catalog'
    | '/dashboard'
    | '/help'
    | '/platform-settings'
    | '/profile'
    | '/releases'
    | '/reports'
    | '/royalties'
    | '/settings'
    | '/support'
    | '/tools'
    | '/users'
    | '/api/dsp-lookup'
    | '/api/generate-image'
    | '/l/$slug'
    | '/admin/tickets'
    | '/releases/$id'
    | '/releases/new'
    | '/tools/dsp-lookup'
    | '/api/public/dsp-webhook/$platform'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pending'
    | '/reset-password'
    | '/analytics'
    | '/approval-queue'
    | '/artists'
    | '/catalog'
    | '/dashboard'
    | '/help'
    | '/platform-settings'
    | '/profile'
    | '/releases'
    | '/reports'
    | '/royalties'
    | '/settings'
    | '/support'
    | '/tools'
    | '/users'
    | '/api/dsp-lookup'
    | '/api/generate-image'
    | '/l/$slug'
    | '/admin/tickets'
    | '/releases/$id'
    | '/releases/new'
    | '/tools/dsp-lookup'
    | '/api/public/dsp-webhook/$platform'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pending'
    | '/reset-password'
    | '/_authenticated/analytics'
    | '/_authenticated/approval-queue'
    | '/_authenticated/artists'
    | '/_authenticated/catalog'
    | '/_authenticated/dashboard'
    | '/_authenticated/help'
    | '/_authenticated/platform-settings'
    | '/_authenticated/profile'
    | '/_authenticated/releases'
    | '/_authenticated/reports'
    | '/_authenticated/royalties'
    | '/_authenticated/settings'
    | '/_authenticated/support'
    | '/_authenticated/tools'
    | '/_authenticated/users'
    | '/api/dsp-lookup'
    | '/api/generate-image'
    | '/l/$slug'
    | '/_authenticated/admin/tickets'
    | '/_authenticated/releases/$id'
    | '/_authenticated/releases/new'
    | '/_authenticated/tools/dsp-lookup'
    | '/api/public/dsp-webhook/$platform'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PendingRoute: typeof PendingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiDspLookupRoute: typeof ApiDspLookupRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  LSlugRoute: typeof LSlugRoute
  ApiPublicDspWebhookPlatformRoute: typeof ApiPublicDspWebhookPlatformRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l/$slug': {
      id: '/l/$slug'
      path: '/l/$slug'
      fullPath: '/l/$slug'
      preLoaderRoute: typeof LSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dsp-lookup': {
      id: '/api/dsp-lookup'
      path: '/api/dsp-lookup'
      fullPath: '/api/dsp-lookup'
      preLoaderRoute: typeof ApiDspLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/royalties': {
      id: '/_authenticated/royalties'
      path: '/royalties'
      fullPath: '/royalties'
      preLoaderRoute: typeof AuthenticatedRoyaltiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/releases': {
      id: '/_authenticated/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof AuthenticatedReleasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform-settings': {
      id: '/_authenticated/platform-settings'
      path: '/platform-settings'
      fullPath: '/platform-settings'
      preLoaderRoute: typeof AuthenticatedPlatformSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/artists': {
      id: '/_authenticated/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof AuthenticatedArtistsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approval-queue': {
      id: '/_authenticated/approval-queue'
      path: '/approval-queue'
      fullPath: '/approval-queue'
      preLoaderRoute: typeof AuthenticatedApprovalQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/dsp-lookup': {
      id: '/_authenticated/tools/dsp-lookup'
      path: '/dsp-lookup'
      fullPath: '/tools/dsp-lookup'
      preLoaderRoute: typeof AuthenticatedToolsDspLookupRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
    '/_authenticated/releases/new': {
      id: '/_authenticated/releases/new'
      path: '/new'
      fullPath: '/releases/new'
      preLoaderRoute: typeof AuthenticatedReleasesNewRouteImport
      parentRoute: typeof AuthenticatedReleasesRoute
    }
    '/_authenticated/releases/$id': {
      id: '/_authenticated/releases/$id'
      path: '/$id'
      fullPath: '/releases/$id'
      preLoaderRoute: typeof AuthenticatedReleasesIdRouteImport
      parentRoute: typeof AuthenticatedReleasesRoute
    }
    '/_authenticated/admin/tickets': {
      id: '/_authenticated/admin/tickets'
      path: '/admin/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/dsp-webhook/$platform': {
      id: '/api/public/dsp-webhook/$platform'
      path: '/api/public/dsp-webhook/$platform'
      fullPath: '/api/public/dsp-webhook/$platform'
      preLoaderRoute: typeof ApiPublicDspWebhookPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedReleasesRouteChildren {
  AuthenticatedReleasesIdRoute: typeof AuthenticatedReleasesIdRoute
  AuthenticatedReleasesNewRoute: typeof AuthenticatedReleasesNewRoute
}

const AuthenticatedReleasesRouteChildren: AuthenticatedReleasesRouteChildren = {
  AuthenticatedReleasesIdRoute: AuthenticatedReleasesIdRoute,
  AuthenticatedReleasesNewRoute: AuthenticatedReleasesNewRoute,
}

const AuthenticatedReleasesRouteWithChildren =
  AuthenticatedReleasesRoute._addFileChildren(
    AuthenticatedReleasesRouteChildren,
  )

interface AuthenticatedToolsRouteChildren {
  AuthenticatedToolsDspLookupRoute: typeof AuthenticatedToolsDspLookupRoute
}

const AuthenticatedToolsRouteChildren: AuthenticatedToolsRouteChildren = {
  AuthenticatedToolsDspLookupRoute: AuthenticatedToolsDspLookupRoute,
}

const AuthenticatedToolsRouteWithChildren =
  AuthenticatedToolsRoute._addFileChildren(AuthenticatedToolsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedApprovalQueueRoute: typeof AuthenticatedApprovalQueueRoute
  AuthenticatedArtistsRoute: typeof AuthenticatedArtistsRoute
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedPlatformSettingsRoute: typeof AuthenticatedPlatformSettingsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReleasesRoute: typeof AuthenticatedReleasesRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRoyaltiesRoute: typeof AuthenticatedRoyaltiesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedAdminTicketsRoute: typeof AuthenticatedAdminTicketsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedApprovalQueueRoute: AuthenticatedApprovalQueueRoute,
  AuthenticatedArtistsRoute: AuthenticatedArtistsRoute,
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedPlatformSettingsRoute: AuthenticatedPlatformSettingsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReleasesRoute: AuthenticatedReleasesRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRoyaltiesRoute: AuthenticatedRoyaltiesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedAdminTicketsRoute: AuthenticatedAdminTicketsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PendingRoute: PendingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiDspLookupRoute: ApiDspLookupRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  LSlugRoute: LSlugRoute,
  ApiPublicDspWebhookPlatformRoute: ApiPublicDspWebhookPlatformRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
